---
title: "HW6"
author: "Chrissy Chen"
date: "2023-11-28"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(boot)
library(broom)
library(readr)
library(modelr)
library(mgcv)
library(dplyr)
```


#### Problem 2
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```
```{r}
lm_weather = lm(tmax ~ tmin + prcp, data = weather_df)

bootstrap_function = function(data, indices) {
  sampled_data = data[indices, ]
  lm_weather = lm(tmax ~ tmin + prcp, data = sampled_data)
  
  rsquared = glance(lm_weather)$r.squared
  coef_product = log(tidy(lm_weather)$estimate[2] * tidy(lm_weather)$estimate[3])
  
  return(c(rsquared, coef_product))
}

set.seed(123)

bootstrap_results <- boot(data = weather_df, statistic = bootstrap_function, R = 5000)

par(mfrow = c(1, 2))  # Set up a 1x2 grid for side-by-side plots
hist(bootstrap_results$t[, 1], main = "Distribution of R-squared", col = "lightblue")
hist(bootstrap_results$t[, 2], main = "Distribution of log(beta1 * beta2)", col = "lightgreen")
par(mfrow = c(1, 1))  # Reset the plot layout

# Identify the 2.5% and 97.5% quantiles
quantiles <- quantile(bootstrap_results$t, c(0.025, 0.975), na.rm = TRUE)
print(quantiles)
```

#### Problem 3
```{r}
birthweight = 
  read_csv("birthweight.csv")

model_1 = lm(bwt ~ delwt + wtgain + blength, data = birthweight)
prediction_1 = add_predictions(birthweight, model_1)
residual_1 = add_residuals(prediction_1, model_1)
ggplot(residual_1,aes(x = pred, y = resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residuals vs Fitted Values", x = "Fitted Values", y = "Residuals")


model_lg = lm(bwt ~ blength + gaweeks, data = birthweight)
prediction_lg = add_predictions(birthweight, model_lg)
residual_lg = add_residuals(prediction_lg, model_lg)
ggplot(residual_lg,aes(x = pred, y = resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residuals vs Fitted Values", x = "Fitted Values", y = "Residuals")


model_hls = lm(bwt ~ bhead * blength * babysex, data = birthweight)
prediction_hls = add_predictions(birthweight, model_hls)
residual_hls = add_residuals(prediction_hls, model_hls)
ggplot(residual_hls,aes(x = pred, y = resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residuals vs Fitted Values", x = "Fitted Values", y = "Residuals")
```
```{r}
cv_df = 
  crossv_mc(birthweight, 100) |>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) |>
  mutate(
    model_1  = map(train, \(df) lm(bwt ~ delwt + wtgain + blength, data = birthweight)),
    model_lg  = map(train, \(df) lm(bwt ~ blength + gaweeks, data = birthweight)),
    model_hls  = map(train, \(df) lm(bwt ~ bhead * blength * babysex, data = birthweight))) |> 
  mutate(
    rmse_1 = map2_dbl(model_1, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_lg = map2_dbl(model_lg, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_hls = map2_dbl(model_hls, test, \(mod, df) rmse(model = mod, data = df))) |>
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

cv_df
```

